version: '1.0'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:             #instruct to construct this service first
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
