services:
  frontend:
    image: satyamshivam/frontend
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: satyamshivam/backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
